export * from "./article-page";
export * from "./blog-page";
export * from "./account-page";
export * from "./catalog-page";
export * from "./cms-page";
export * from "./login-page";
export * from "./not-found-page";
export * from "./product-page";
export * from "./register-page";
